### ISSUE TITLE
After update fatal error

### ISSUE THREAD

**Issue by ThoMagnum** [NathanVaughn/webtrees-docker#101]
**Edit: I did a reinstallation especially to renew the "config.ini.php", now everything works as expected.**

Tonight watchtower updated my docker container to the latest available. If I now open the webtree page I get the following error. Any ideas what happened or what's the reason for this error?
Unfortunately I am not very skilled and don't understand the error.

_Fatal error: During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Container\Container::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/webtrees/vendor/illuminate/container/Container.php:1214 Stack trace: #0 /var/www/webtrees/vendor/illuminate/container/Container.php(15): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(8192, 'Return type of ...', '/var/www/webtre...', 1214) #1 /var/www/webtrees/vendor/composer/ClassLoader.php(571): include('/var/www/webtre...') #2 /var/www/webtrees/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/var/www/webtre...') #3 /var/www/webtrees/app/Webtrees.php(300): Composer\Autoload\ClassLoader->loadClass('Illuminate\\Cont...') #4 /var/www/webtrees/app/Webtrees.php(220): Fisharebest\Webtrees\Webtrees::set('Psr\\Http\\Messag...', 'Nyholm\\Psr7\\Fac...') #5 /var/www/webtrees/index.php(44): Fisharebest\Webtrees\Webtrees->httpRequest() #6 {main} in /var/www/webtrees/vendor/illuminate/container/Container.php on line 15_

I disabled every Module, so this should not be the issue.

**Comment by ThoMagnum** [comment]
**Edit: I did a reinstallation especially to renew the "config.ini.php", now everything works as expected.**
